version: '3.8'

services:
  frontend:
    build:
      context: ./next-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./go-backend
    ports:
      - "8000:8000"

