version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"  
    depends_on:
      - backend

  backend:
    build:
      context: ./go-backend
    container_name: go-backend
    ports:
      - "8000:8000"

